<a href="https://colab.research.google.com/github/marioabdelsayed/ComparingHospitals/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Team Madridistas
> Mario Abdelsayed (marioa2@illinois.edu) & Luis Ramos (lframos2@illinois.edu)

---

## Data Cleaning

The following data cleaning procedures aimed to ensure data accuracy, consistency, and reliability, to allow for a
proper analysis of menu items from the NYPL dataset over the `Dish` table. These tasks were performed using a variety
of tools including OpenRefine, and Python libraries such as `pandas` and `pandasql` using Jupyter Notebooks.

**Clustering** using OpenRefine was the first step in our process. Menu items may have been recorded with variations in
spelling or naming conventions (e.g., "spaghetti" vs. "spagetti").
Clustering dish names helped to aggregate similar items, reducing redundancy and improving accuracy in identifying popular
items. A crucial step for ensuring that items were not counted multiple times due to naming discrepancies, thus
providing an accurate count of appearances within the specified price range.

**Entry Normalization**. Inconsistent casing and spacing can result in duplicate entries being treated as separate items.
Normalizing aspects such as casing and spacing ensures uniformity across the dataset. OpenRefine was the ideal tool to
achieve this action. Performing this task allowed us to prevent duplication and misinterpretation of menu items due to
formatting inconsistencies, thereby supporting accurate item popularity analysis.

**Plotting columns** aided in visualizing the `first_appeared` and `last_appeared` columns helps to identify anomalies,
such as items with dates that fall outside expected ranges or have unusual gaps in their appearance history.
OpenRefine's facets feature was key to find the entries that were to be removed. Once these wrongful entries were pruned
from the dataset, we could confidently verify the temporal data's integrity, ensuring that only valid timeframes were
considered when analyzing the popularity of menu items.

**Removal of outliers and entries that are clearly false** ensured the dataset's integrity. To perform this task,
Python using `pandas` was preferred tool. Outliers, such as a `last_appeared` year of 2928, are clearly erroneous
and can skew analysis results. This step was critical to ensure that the analysis was based on realistic and credible
data, particularly since U<sub>1</sub> requires querying over a specific year range.

**Removal of empty records** (records with zero values across all columns) using Python allowed us to remove entries
that do not contribute to the analysis and may introduce noise into the dataset. Applying this procedure to our dataset
meant that only meaningful data will be present in the dataset for a valid analysis.

After performing these steps, the team was able to achieve all the cleaning steps we set out to do in Phase-I to bring
the dataset to an analysis-ready state.

## Data Quality

### Summary of Changes
---

|Defect|Operation|Columns changed and Count|Rows changed (Count)|
|:----|:----|:----|:----|
|Values of 0 in first_appeared Column|Convert 0 to -1 to indicate invalid|first_appeared |552875|
|Values of 1 in first_appeared Column|Convert 1 to -1 to indicate invalid|first_appeared |205|
|Values of 2928 in first_appeared|Converted 2928 to -1 to indicate invalid|first_appeared |11|
|First_appeared is not a number column|Converted first_appeared to a numeric column|first_appeared|All rows|
|Values of 0 in last_appeared Column|Convert 0 to -1 to indicate invalid|last_appeared |55000|
|Values of 1 in last_appeaered|Convered 1 to -1 to indicate invalid|last_appeared |37|
|Values of 2928 in last_appeared|Converted 2928 to -1 to indicate invalid|last_appeared|179|
|Last_appeared is not a numeric column|Converted last_appeared to a numeric column|Last_appeard|All rows|
|Empty records (Nulls or zeros across all columns)|Removed records|All columns|2271|
|Value of -1 in Times appeared |Removed records|All columns|15|
|Value of -2 in Times appeared|Removed records|All columns|3|
|Value of -3 in Times appeared|Removed records|All columns|2|
|Value of -6 in Times appeared|Removed records|All columns|1|
|Value of 0 in Times appeared|Removed records|All columns|9248|
|Invalid first_appeared records (-1 values)|Removed records|All columns|50790Records in violation of constraint 3|Removed records|All columns|869|
|Records in violation of constraint 4|Removed records|All columns|169|
|Records in violation of constraint 6|Removed records|All columns|14456|


## **Constraint Violaions Report**
The following is a comparison between the original state of the data and the final state after cleaning by querying for constraint violations and comparing the output

In [ ]:
clean_dish = pd.read_csv('Dish-clean.csv')
dirty_dish = pd.read_csv('Dish.csv')

### **Constraint 1: If an entry is in the data, then it must appear in at least one menu**

**Original Data**

In [ ]:
sqldf('''SELECT *
          FROM dirty_dish
          WHERE times_appeared < 1
''')

,id,name,description,menus_appeared,times_appeared,first_appeared,last_appeared,lowest_price,highest_price
0,825,"Rice, Semolina",None,1,0,1900,1900,0.00,0.00
1,2799,""" "" half pint",None,1,0,1901,1901,0.10,0.10
2,3031,""" saute with mushrooms",None,1,0,1900,1900,0.00,0.00
3,3032,""" a la Lyonnaise",None,1,0,1900,1900,0.35,0.35
4,3033,""" en brochette",None,1,0,1900,1900,0.50,0.50
...,...,...,...,...,...,...,...,...,...
9264,515602,Fig Cômpote,None,1,0,0,0,0.00,0.00
9265,515604,Compôte of Apricots,None,0,0,0,0,0.00,0.00
9266,515620,Filet de Soles à l'Amiral,None,0,0,0,0,0.00,0.00
9267,515646,Lebendfrischer Helgoländer Hummer - Zubereitun...,None,0,0,0,0,0.00,0.00
9268,515655,François President Brut,None,0,0,0,0,0.00,0.00

**Clean Data**

In [ ]:
#df[df['times_appeared'] < 1]
sqldf('''SELECT *
          FROM clean_dish
          WHERE times_appeared < 1
''')

Empty DataFrame
Columns: [id, name, description, menus_appeared, times_appeared, first_appeared, last_appeared, lowest_price, highest_price]
Index: []



## **Constraint 2: An item cannot have an appearance in a future date**

**Original Data**

In [ ]:
sqldf('''SELECT *
          FROM dirty_dish
          WHERE first_appeared > 2024 OR last_appeared > 2024
''')

,id,name,description,menus_appeared,times_appeared,first_appeared,last_appeared,lowest_price,highest_price
0,7,Radishes,None,3262,3346,1854,2928,0.0,25.0
1,15,Celery,None,4246,4690,1,2928,0.0,50.0
2,18,Sardines,None,1425,1484,1856,2928,0.0,50.0
3,33,Sliced Tomatoes,None,1195,1256,1873,2928,0.0,25.0
4,96,Coffee,None,7740,8484,1,2928,0.0,30.0
...,...,...,...,...,...,...,...,...,...
174,415520,"Guinea chicken saute, fresh mushrooms",None,1,1,2928,2928,1.0,1.0
175,415521,"Spring chicken fricassee, family style",None,1,1,2928,2928,0.9,0.9
176,415523,Roast baby lamb with mint sauce,None,1,1,2928,2928,0.7,0.7
177,415525,"Broiled sweetbreads, Infante",None,1,1,2928,2928,0.7,0.7
178,415526,"Broiled pork tenderloin, fried parsnips",None,1,1,2928,2928,0.7,0.7

**Clean Data**

In [ ]:
sqldf('''SELECT *
          FROM clean_dish
          WHERE first_appeared > 2024 OR last_appeared > 2024
''')

Empty DataFrame
Columns: [id, name, description, menus_appeared, times_appeared, first_appeared, last_appeared, lowest_price, highest_price]
Index: []

## **Constraint 3: An item cannot appear more times than menus it appeared in**

**Original Data**

In [ ]:
sqldf('''SELECT *
          FROM dirty_dish
          WHERE menus_appeared > times_appeared
''')

,id,name,description,menus_appeared,times_appeared,first_appeared,last_appeared,lowest_price,highest_price
0,208,Luncheon,None,19,18,1900,1993,0.65,0.65
1,825,"Rice, Semolina",None,1,0,1900,1900,0.00,0.00
2,1082,Caviare,None,86,85,1888,1906,0.40,0.50
3,1136,Carta blanca,None,8,7,1900,1981,0.00,0.00
4,1346,Hackley's Sour Mash,None,5,4,1900,1900,0.15,0.15
...,...,...,...,...,...,...,...,...,...
8269,515598,Apricot Cômpote,None,1,0,0,0,0.00,0.00
8270,515599,Pear Cômpote,None,1,0,0,0,0.00,0.00
8271,515600,Guava Cômpote,None,1,0,0,0,0.00,0.00
8272,515601,Bilberies Cômpote,None,1,0,0,0,0.00,0.00
8273,515602,Fig Cômpote,None,1,0,0,0,0.00,0.00

**Clean Data**

In [ ]:
sqldf('''SELECT *
          FROM clean_dish
          WHERE menus_appeared > times_appeared
''')

Empty DataFrame
Columns: [id, name, description, menus_appeared, times_appeared, first_appeared, last_appeared, lowest_price, highest_price]
Index: []

## **Constraint 4: An item cannot first appear before its last appearance**

**Original Data**

In [ ]:
sqldf('''SELECT *
          FROM dirty_dish
          WHERE first_appeared > last_appeared
''')

,id,name,description,menus_appeared,times_appeared,first_appeared,last_appeared,lowest_price,highest_price
0,164029,Clear beef broth,None,0,1,1900,0,0.25,0.25
1,204888,Hot roast beef with gravy,None,0,1,1900,0,0.25,0.25
2,250693,SURI LEBERLI - Shredded Calf's Liver Flambe in...,None,0,1,1945,0,NaN,NaN
3,250699,"SWISS MINCED VEAL, ROESTI",None,0,1,1945,0,NaN,NaN
4,301736,Cafe Glacee,None,0,2,1940,0,0.40,0.40
5,309629,Garlic Butter,None,0,1,1947,0,0.40,0.40

**Clean Data**

In [ ]:
sqldf('''SELECT *
          FROM clean_dish
          WHERE first_appeared > last_appeared
''')

Empty DataFrame
Columns: [id, name, description, menus_appeared, times_appeared, first_appeared, last_appeared, lowest_price, highest_price]
Index: []

## **Constraint 5: An item's lowest price cannot be higher than its highest price**

**Original Data**

In [ ]:
sqldf('''SELECT *
          FROM dirty_dish
          WHERE lowest_price > highest_price
''')

Empty DataFrame
Columns: [id, name, description, menus_appeared, times_appeared, first_appeared, last_appeared, lowest_price, highest_price]
Index: []

In this case, the original data didn't contain any violations. Let's make sure we didn't introduce any.

**Clean Data**

In [ ]:
#df[(df['lowest_price'] > df['highest_price'])]
sqldf('''SELECT *
          FROM clean_dish
          WHERE lowest_price > highest_price
''')

Empty DataFrame
Columns: [id, name, description, menus_appeared, times_appeared, first_appeared, last_appeared, lowest_price, highest_price]
Index: []

## **Constraint 6: If an item appeared only once, then its highest and lowest price must be equal**

**Original Data**

In [ ]:
sqldf('''SELECT *
          FROM dirty_dish
          WHERE times_appeared = 1 AND lowest_price != highest_price
''')

,id,name,description,menus_appeared,times_appeared,first_appeared,last_appeared,lowest_price,highest_price
0,1221,Lanoire,None,1,1,1900,1900,1.75,3.50
1,1329,Crabs deviled,None,1,1,1900,1900,0.30,0.50
2,1477,La Rosa Zinfandel (C. V. & Co.),None,1,1,1900,1900,0.25,0.50
3,1490,"Geo. Goulet, Ay Brut, 1884",None,1,1,1900,1900,2.00,3.75
4,1738,YELLOW LABEL,None,1,1,1901,1901,1.75,3.50
...,...,...,...,...,...,...,...,...,...
14939,513413,Milk Fed Veal Cutlet Parmigiano,None,1,1,0,0,2.25,3.25
14940,513414,Scaloppine of Veal Marsala With Mushrooms,None,1,1,0,0,2.50,3.50
14941,513415,Breast of Capon Puccini,None,1,1,0,0,2.75,3.75
14942,513416,Minute Steak Broiled,None,1,1,0,0,3.50,4.50
14943,513417,Minute Steak Saute Marinara Sauce,None,1,1,0,0,3.50,4.50

**Clean Data**

In [ ]:
sqldf('''SELECT *
          FROM clean_dish
          WHERE times_appeared = 1 AND lowest_price != highest_price
''')

Empty DataFrame
Columns: [id, name, description, menus_appeared, times_appeared, first_appeared, last_appeared, lowest_price, highest_price]
Index: []

## Workflow
![YesWorkflow](/img/workflow.png)

## Conclusion

For our purposes, we found it useful to use a variety of tools such as OpenRefine, and Python using different libraries
such as pandas. Each tool helped us achieved different cleaning steps. We only scratched the surface of cleaning this dataset,
there are definitely more tools available that we did not take advantage of. We were surprised to find a vast number of
integrity violations on this dataset, given the fact that the dataset is seemingly clean at first sight.
One of the problems we encountered was clustering a column with a large number of rows, due to low memory on our
computer systems.